### ISSUE TITLE
Support Cilium

### ISSUE THREAD

**Issue by adrienjt** [gardener/gardener-extension-networking-cilium#1]
**What would you like to be added**:

I would like support for Cilium.

As I understand from reading https://github.com/gardener/gardener/issues/686, this will be possible when CNI extensibility is implemented. Is that actively being worked on, on the roadmap? If not, any pointers on what's needed?

In the meantime, what would happen if I installed Cilium in a shoot cluster? Would Gardener revert some of my changes to try to re-enable Calico?

**Why is this needed**:

Cilium security features and cluster mesh.

**Comment by zanetworker** [comment]
@soumynathan any update on this issue? if you need help let us know :)

**Comment by soumynathan** [comment]
I have some doubts on the controller for the network extension. @zanetworker I sent you an email, we might need to have another session to go over this.

**Comment by soumynathan** [comment]
@zanetworker  @rfranzke I do see that there is a new branch that has been created by @rfranzke for cilium extension. Should I be using that branch going forward.

**Comment by zanetworker** [comment]
@soumynathan yes indeed, this is now a separate repo, easier to test and consume.

**Comment by soumynathan** [comment]
@zanetworker @rfranzke I have moved my work to the new repo.
Here is the new pull request. We can starting working here.
https://github.com/gardener/gardener-extension-networking-cilium/pull/4

**Comment by soumynathan** [comment]
Good job. It finally merged.
