### ISSUE TITLE
Support Cilium v1.10

### ISSUE THREAD

**Issue by briantopping** [gardener/gardener-extension-networking-cilium#48]
**How to categorize this issue?**

/area operations
/area networking
/kind enhancement
/priority 4

**What would you like to be added**:
[Cilium v1.10](https://cilium.io/blog/2021/05/20/cilium-110) has quite a few new features that would be helpful in bare-metal Gardener deployments, such as IP egress and BGP integration via MetalLB.

**Comment by DockToFuture** [comment]
We are supporting cilium v1.10.x since https://github.com/gardener/gardener-extension-networking-cilium/commit/8278ec5ecde85afdb3d228acb73f04918b85b150.

**Comment by briantopping** [comment]
Oh that's great, thank you for the hard work! 

If I may ask, is there any discussion on disabling `kubeProxyReplacement`? I've been running with this turned on for my single seed cluster. Handling KubeProxy from BPF maps is a huge performance win, though it seems that the size of the maps may have to be tuned to support a Garden. 

Thank you! Hope your summer is going well.
