### ISSUE TITLE
Use Etcdruid as for managing Cilium storage

### ISSUE THREAD

**Issue by zanetworker** [gardener/gardener-extension-networking-cilium#8]
**What would you like to be added**:
Currently there are two options for cilium storage, namely, CRDs or Cilium operated Etcd. In Gardener however we already have an Etcd operator which we can utilize here as well (https://github.com/gardener/etcd-druid). 

cc @swapnilgm

**Comment by ScheererJ** [comment]
We only support kubernetes as data store and do not intend to change this.
/close
